import { ITimezone } from '../timeZones.interface'

export const allTimeZones: ITimezone[] = [
  { country: 'UTC', zone: 'UTC', flag: 'utc' },
  { country: 'Andorra', zone: 'Europe/Andorra', flag: 'ad' },
  { country: 'Emiratos Árabes Unidos', zone: 'Asia/Dubai', flag: 'ae' },
  { country: 'Afganistán', zone: 'Asia/Kabul', flag: 'af' },
  { country: 'Albania', zone: 'Europe/Tirane', flag: 'al' },
  { country: 'Armenia', zone: 'Asia/Yerevan', flag: 'am' },
  { country: 'Antártida', zone: 'Antarctica/Troll', flag: 'aq' },
  { country: 'Argentina', zone: 'America/Argentina/Buenos_Aires', flag: 'ar' },
  { country: 'Austria', zone: 'Europe/Vienna', flag: 'at' },
  { country: 'Australia (Sydney)', zone: 'Australia/Sydney', flag: 'au' },
  { country: 'Azerbaiyán', zone: 'Asia/Baku', flag: 'az' },
  { country: 'Barbados', zone: 'America/Barbados', flag: 'bb' },
  { country: 'Bangladés', zone: 'Asia/Dhaka', flag: 'bd' },
  { country: 'Bélgica', zone: 'Europe/Brussels', flag: 'be' },
  { country: 'Bolivia', zone: 'America/La_Paz', flag: 'bo' },
  { country: 'Brasil (Noronha)', zone: 'America/Noronha', flag: 'br' },
  { country: 'Brasil (São Paulo)', zone: 'America/Sao_Paulo', flag: 'br' },
  { country: 'Brasil (Manaos)', zone: 'America/Manaus', flag: 'br' },
  { country: 'Brasil (Rio Branco)', zone: 'America/Rio_Branco', flag: 'br' },
  { country: 'Colombia', zone: 'America/Bogota', flag: 'co' },
  { country: 'Costa Rica', zone: 'America/Costa_Rica', flag: 'cr' },
  { country: 'Ecuador', zone: 'America/Guayaquil', flag: 'ec' },
  { country: 'Ecuador (Galápagos)', zone: 'Pacific/Galapagos', flag: 'ec' },
  { country: 'España', zone: 'Europe/Madrid', flag: 'es' },
  { country: 'Chile', zone: 'America/Santiago', flag: 'cl' },
  { country: 'México', zone: 'America/Mexico_City', flag: 'mx' },
  { country: 'México (Tijuana)', zone: 'America/Tijuana', flag: 'mx' },
  { country: 'México (Cancún)', zone: 'America/Cancun', flag: 'mx' },
  { country: 'México (Chihuahua)', zone: 'America/Chihuahua', flag: 'mx' },
  { country: 'Nicaragua', zone: 'America/Managua', flag: 'ni' },
  { country: 'Países Bajos', zone: 'Europe/Amsterdam', flag: 'nl' },
  { country: 'Noruega', zone: 'Europe/Oslo', flag: 'no' },
  { country: 'Nepal', zone: 'Asia/Kathmandu', flag: 'np' },
  { country: 'Nauru', zone: 'Pacific/Nauru', flag: 'nr' },
  { country: 'Niue', zone: 'Pacific/Niue', flag: 'nu' },
  { country: 'Nueva Zelanda', zone: 'Pacific/Auckland', flag: 'nz' },
  { country: 'Panamá', zone: 'America/Panama', flag: 'pa' },
  { country: 'Perú', zone: 'America/Lima', flag: 'pe' },
  { country: 'Filipinas', zone: 'Asia/Manila', flag: 'ph' },
  { country: 'Pakistán', zone: 'Asia/Karachi', flag: 'pk' },
  { country: 'Polonia', zone: 'Europe/Warsaw', flag: 'pl' },
  { country: 'San Pedro y Miquelón', zone: 'America/Miquelon', flag: 'pm' },
  { country: 'Pitcairn', zone: 'Pacific/Pitcairn', flag: 'pn' },
  { country: 'Puerto Rico', zone: 'America/Puerto_Rico', flag: 'pr' },
  { country: 'Palestina (Gaza)', zone: 'Asia/Gaza', flag: 'ps' },
  { country: 'Palestina (Hebrón)', zone: 'Asia/Hebron', flag: 'ps' },
  { country: 'Portugal', zone: 'Europe/Lisbon', flag: 'pt' },
  { country: 'Portugal (Azores)', zone: 'Atlantic/Azores', flag: 'pt' },
  { country: 'Palau', zone: 'Pacific/Palau', flag: 'pw' },
  { country: 'Paraguay', zone: 'America/Asuncion', flag: 'py' },
  { country: 'Qatar', zone: 'Asia/Qatar', flag: 'qa' },
  { country: 'Reunión', zone: 'Indian/Reunion', flag: 're' },
  { country: 'Rumania', zone: 'Europe/Bucharest', flag: 'ro' },
  { country: 'Serbia', zone: 'Europe/Belgrade', flag: 'rs' },
  { country: 'Rusia (Kaliningrado)', zone: 'Europe/Kaliningrad', flag: 'ru' },
  { country: 'Rusia (Moscú)', zone: 'Europe/Moscow', flag: 'ru' },
  { country: 'Rusia (Samara)', zone: 'Europe/Samara', flag: 'ru' },
  { country: 'Rusia (Yekaterimburgo)', zone: 'Asia/Yekaterinburg', flag: 'ru' },
  { country: 'Rusia (Omsk)', zone: 'Asia/Omsk', flag: 'ru' },
  { country: 'Rusia (Krasnoyarsk)', zone: 'Asia/Krasnoyarsk', flag: 'ru' },
  { country: 'Rusia (Irkutsk)', zone: 'Asia/Irkutsk', flag: 'ru' },
  { country: 'Rusia (Yakutsk)', zone: 'Asia/Yakutsk', flag: 'ru' },
  { country: 'Rusia (Vladivostok)', zone: 'Asia/Vladivostok', flag: 'ru' },
  { country: 'Arabia Saudita', zone: 'Asia/Riyadh', flag: 'sa' },
  { country: 'Islas Salomón', zone: 'Pacific/Guadalcanal', flag: 'sb' },
  { country: 'Seychelles', zone: 'Indian/Mahe', flag: 'sc' },
  { country: 'Sudán', zone: 'Africa/Khartoum', flag: 'sd' },
  { country: 'Suecia', zone: 'Europe/Stockholm', flag: 'se' },
  { country: 'Singapur', zone: 'Asia/Singapore', flag: 'sg' },
  { country: 'Surinam', zone: 'America/Paramaribo', flag: 'sr' },
  { country: 'Sudán del Sur', zone: 'Africa/Juba', flag: 'ss' },
  { country: 'Santo Tomé y Príncipe', zone: 'Africa/Sao_Tome', flag: 'st' },
  { country: 'El Salvador', zone: 'America/El_Salvador', flag: 'sv' },
  { country: 'Siria', zone: 'Asia/Damascus', flag: 'sy' },
  { country: 'Chad', zone: 'Africa/Ndjamena', flag: 'td' },
  { country: 'Tailandia', zone: 'Asia/Bangkok', flag: 'th' },
  { country: 'Tayikistán', zone: 'Asia/Dushanbe', flag: 'tj' },
  { country: 'Turkmenistán', zone: 'Asia/Ashgabat', flag: 'tm' },
  { country: 'Túnez', zone: 'Africa/Tunis', flag: 'tn' },
  { country: 'Turquía', zone: 'Europe/Istanbul', flag: 'tr' },
  { country: 'Ucrania', zone: 'Europe/Kiev', flag: 'ua' },
  {
    country: 'USA (East)',
    zone: 'America/New_York',
    flag: 'us',
  },
  {
    country: 'USA (Center)',
    zone: 'America/Chicago',
    flag: 'us',
  },
  {
    country: 'USA (Mountain)',
    zone: 'America/Denver',
    flag: 'us',
  },
  {
    country: 'USA (Pacific)',
    zone: 'America/Los_Angeles',
    flag: 'us',
  },
  {
    country: 'USA (Alaska)',
    zone: 'America/Anchorage',
    flag: 'us',
  },
  {
    country: 'USA (Hawaii)',
    zone: 'Pacific/Honolulu',
    flag: 'us',
  },

  { country: 'Uruguay', zone: 'America/Montevideo', flag: 'uy' },
  { country: 'Uzbekistán', zone: 'Asia/Tashkent', flag: 'uz' },
  { country: 'Venezuela', zone: 'America/Caracas', flag: 've' },
  { country: 'Vietnam', zone: 'Asia/Ho_Chi_Minh', flag: 'vn' },
  { country: 'Sudáfrica', zone: 'Africa/Johannesburg', flag: 'za' },
]
